# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: download label

on:
  schedule:
    - cron: '40 18 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size=2gb

    steps:
    - uses: actions/checkout@v4
    - name: Install xvfb
      run: sudo apt-get install -y --quiet --assume-yes xvfb libnss3-dev ca-certificates libxss1 libappindicator3-1 libindicator7 fonts-liberation libdbus-1-3 curl
    - name: update permission
      run: sudo chmod ugo+w /var/log
#    - name: Setup Chrome
#      uses: browser-actions/setup-chrome@v1
#      with:
#        chrome-version: 137.0.7151.119
#        install-dependencies: true
#        install-chromedriver: true
#    - run: chrome --version
    - name: update packages
      run: sudo apt-get --fix-broken --assume-yes install
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for Selenium
      run: |
        for i in {1..60}; do
          if curl -s http://localhost:4444/wd/hub/status > /dev/null; then
            echo "Selenium is ready"
            break
          fi
          echo "Waiting for Selenium... ($i/60)"
          sleep 1
        done
    - name: download labels
      run: |
#        Xvfb :99 -screen 0 1024x768x24 &
#        export DISPLAY=:99
        # stop the build if there are Python syntax errors or undefined names
#        xvfb-run -a -s "-screen 0 1920x1080x24" robot --variable REMOTE_URL:http://localhost:4444 --outputdir results --include meesho .
        robot --variable REMOTE_URL:http://localhost:4444 --outputdir results --include meesho .
